services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT api.app:app
    envVars:
      - key: GEMINI_API_KEY
        fromDatabase:
          value: ${gemini-api-key}
      - key: CLASS_MODEL_PATH
        value: api/models/classificationbest.pt
      - key: DETECT_MODEL_PATH
        value: api/models/detectionbest.pt
      - key: NODEJS_URL
        fromDatabase:
          value: ${nodejs-url}
      - key: PYTHON_VERSION
          value: 3.9
    autoDeploy: true

  - type: web
    name: node-app
    env: node
    buildCommand: npm install
    startCommand: node node-backend/index.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          value: ${mongodb-uri}
      - key: NODE_VERSION
        value: 18
    autoDeploy: true