services:
  - type: web
    name: flask-app
    env: python
    rootDir: api/
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: GEMINI_API_KEY
        value: AzIaSyDp3-7PBLlp_5DQmLQitH9B-ETqsZgx-Gg  # Replace with secure method if needed
      - key: CLASS_MODEL_PATH
        value: models/classificationbest.pt
      - key: DETECT_MODEL_PATH
        value: models/detectionbest.pt
      - key: NODEJS_URL
        value: https://node-app.onrender.com/store-results  # Update after Node.js deployment
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true

  - type: web
    name: node-app
    env: node
    rootDir: node-backend/
    buildCommand: yarn install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://omnbhaltilak:7jWkAhqwv6MbfE3w@cluster0.xhycs.mongodb.net/verification_db?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
