services:
  # Frontend: Static site
  - type: web
    name: my-render-app-frontend
    env: static
    staticPublishPath: .
    buildCommand: echo "No build step needed for static site"
    startCommand: python3 -m http.server 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend: Flask app (Python)
  - type: web
    name: my-render-app-flask-backend
    env: python
    build:
      context: .
      command: |
        pip install --upgrade pip
        pip install --no-cache-dir flask==2.3.2
        pip install --no-cache-dir ultralytics==8.0.0
        pip install --no-cache-dir easyocr==1.7.0
        pip install --no-cache-dir flask-cors==3.0.10
        pip install --no-cache-dir gunicorn==20.1.0
        pip install --no-cache-dir pandas==1.5.3
        pip install --no-cache-dir opencv-python==4.5.5.64
        pip install --no-cache-dir google-generativeai==0.1.0
        pip install --no-cache-dir fuzzywuzzy==0.18.0
        pip install --no-cache-dir python-Levenshtein==0.20.9
        pip install --no-cache-dir requests==2.28.1
        pip show gunicorn
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: GEMINI_API_KEY
        sync: false
      - key: CLASS_MODEL_PATH
        value: models/classification_best.pt
      - key: DETECT_MODEL_PATH
        value: models/detection_best.pt
      - key: NODEJS_URL
        value: https://my-render-app-node-backend.onrender.com/store-results
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 5000

  # Backend: Node.js app
  - type: web
    name: my-render-app-node-backend
    env: node
    workingDir: node-backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: verification_db
    databaseName: verification_db
    user: admin
