services:
  # Frontend: Static site
  - type: web
    name: my-render-app-frontend
    env: static
    staticPublishPath: .
    buildCommand: echo "No build step needed for static site"
    startCommand: python3 -m http.server 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend: Flask app (Python)
  - type: web
    name: my-render-app-flask-backend
    env: python
    build:
      context: .
      command: pip install --upgrade pip && pip install --no-cache-dir -r api/requirements.txt && pip show gunicorn
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: GEMINI_API_KEY
        sync: false
      - key: CLASS_MODEL_PATH
        value: models/classification_best.pt
      - key: DETECT_MODEL_PATH
        value: models/detection_best.pt
      - key: NODEJS_URL
        value: https://my-render-app-node-backend.onrender.com/store-results
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 5000

  # Backend: Node.js app
  - type: web
    name: my-render-app-node-backend
    env: node
    workingDir: node-backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000

databases:
  - name: verification_db
    databaseName: verification_db
    user: admin
